### ISSUE TITLE
Missing either an "out" or "dir" config value when running grunt requirejs

### ISSUE THREAD

**Issue by gremo** [tbranyen/backbone-boilerplate#135]
Any help in solving this would be much appreciated. Running `grunt requirejs` gives me:

```
Running "requirejs:mainConfigFile" (requirejs) task
    >> Error: Missing either an "out" or "dir" config value. If using "appDir" for a full project 
    optimization, use "dir". If you want to optimize to one file, use "out".

    at Function.build.createConfig
    (C:\Users\XXX\AppData\Roaming\npm\node_modules\grunt\node_modules\requirejs\bin\r.js)
Aborted due to warnings.
```

**Comment by lauradaniela** [comment]
I have the same error when execute grunt
the message is
D:\LauraAcosta\Fuentes Estadisticas\AgronetEstadisticas-master>grunt requirejs
Running "requirejs:dist" (requirejs) task
>> Error: Error: Missing either an "out" or "dir" config value. If using "appDir" for a full project optimization, use "dir". If you want to optimize to one file, use "out".
>>     at Function.build.createConfig (D:\LauraAcosta\Fuentes Estadisticas\AgronetEstadisticas-master\node_modules\grunt-requirejs\node_modules\requirejs\bin\r.js:31109:19)
Warning: Task "requirejs:dist" failed. Use --force to continue.

**Comment by tbranyen** [comment]
RequireJS isn't used anymore so you're on something very old.  You'll have to debug the Grunt error.
