### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by addyosmani** [tbranyen/backbone-boilerplate#14]
As requested, here's my feedback and suggestions for the project:

* I would consider switching out QUnit as the default testing framework of choice in lieu of Jasmine. Whilst QUnit is great and is generally considered de facto when it comes to testing jQuery plugins, I've personally found that more Backbone developers use Jasmine. There's also a considerable amount of more documentation, tutorials and articles about using Jasmine/BDD to test both standard Backbone and RequireJS + BB apps and authors currently writing BB books (other than myself) seem to be opting for it as well. Having spoken to Irene, I know that BB is officially using QUnit for it's own unit tests, but as many of us agree they suck, I don't think we could consider it a good example we could point people at to make-up for the lack of tuts. In this light, I feel it would make more sense and as both QUnit and Jasmine can be easily swapped, perhaps it's not that big of a change to make. 

* Have you given any thoughts to internationalization? I'm not sure whether this is something that you would like developers to think about more but it might be useful to provide some boilerplate code that demonstrates how to support i18n. Script loaders like Require.js certainly support this out of the box but maybe it would be of benefit to show people how to support it without? Would definitely help convince those with English as a second language to seriously consider using this.

* In the architectural/filesystem pattern being used, each block of models/views/collections are wrapped within individual modules which we're explicitly calling 'modules' . It's something which may have been discussed in the comments section of the original post by Tim and Irene, but there are developers who are used to either wrapping each view/model/collection into it's own 'module' using RequireJS and AMD whilst others are used to MVC being kept separate and 'modules' only being utility blocks which views etc. access. I think that (especially given the first) it might be of use to clarify how this boilerplate might sit in a RequireJS backed application - maybe even just on the wiki or somewhere else. Fwiw, in my discussions with some of the Yahoo/YUILibrary folk, they actually describe a module/view/collection block wrapped in this manner as a 'widget'. Soo much terminology, so many different meanings :)

* I see that Ben's grunt solution is currently being used as a part of the build process. I haven't had a chance to review it in great depth just yet, but perhaps it would be of benefit to document/discuss why grunt (or other parts of the build process) were opted for over other solutions. Just playing devil's advocate, some BB developers might wonder why they would want to use this over say something with r.js or based on Rake/Jake etc.

* With respect to https://github.com/tbranyen/backbone-boilerplate/issues/10, are you looking for something that allows you to automatically reload when files get changed? I took a very preliminary look into this for H5BP and I know that @mklabs has definitely done more work on this for a few projects. Might be worth reaching out to see if he might be able to help with this.

* Would it be useful at all for there to be an adjacent 'sample' project (say a Todo app or a multi-view gallery) which is based on Backbone Boilerplate? Looking at it from the perspective of a new developer, I would be interested in seeing how one might structure an application using these module blocks of MVC vs. what the common Backbone apps that come with the framework might do out of the box. It could just be me that feels this would be useful, but just thinking of what would help lower confusion.

* Regarding https://github.com/tbranyen/backbone-boilerplate/issues/6, do you mean Backbone plugins or build-process plugins? :) If you're referring to the former, I think it might be a challenge to find a common set of Backbone add-ons that are used for every project. It would however be useful to maintain a useful list of these in the wiki.

Hope some of this is of help :)

**Comment by tbranyen** [comment]
This issue has long since been stagnant, closing now and forever hold its peace.
