### ISSUE TITLE
packaging multiple modules

### ISSUE THREAD

**Issue by LeeFrancis** [tbranyen/backbone-boilerplate#186]
I am fairly new to backbone and bbb but what I have played with so far I am a huge fan off.
One question I have is that I would like to split my app into modules and have those modules compiled into single files.
I can then target those javascript files to be loaded when I hit certain functionality of the app.
Looking at the requirejs optimizer I can use the modules approach :
({
    dir: "dist/debug",
    modules: [
        {
            name: "modules/module1"
        },
        {
            name: "modules/module2"
        }
    ]
})

but when I do this and remove the name:config and the out:"dist/debug/require.js" from my grunt.js file bbb release fails in require.js with a no such file or directory '/vendor/js/libs.js'.
Am I going about this the wrong way?

Thanks,

Lee.

**Comment by tbranyen** [comment]
Closing this stagnant issue.
