### ISSUE TITLE
PhoneGap + bbb

### ISSUE THREAD

**Issue by santiago** [tbranyen/backbone-boilerplate#193]
Hi, I'm somewhat lost trying to integrate with PhoneGap. My app looks ok when loaded in browser and grabs templates from JST when running with bbb server. 

I followed https://github.com/tbranyen/backbone-boilerplate/wiki/Filesystem and opened the app from file:/// --it fails from localhost-- but it tries fetching template rather than using JST.

I suppose that pointing index.html to those files in dist/release might work, but I hear I should not modify it.

Thanks

**Comment by tbranyen** [comment]
Closing stagnant issue.
