### ISSUE TITLE
Add debugging best practices/patterns

### ISSUE THREAD

**Issue by SBoudrias** [tbranyen/backbone-boilerplate#200]
I wonder if it could be a neat addition to add information/boilerplate code about debugging.

When I deploy an application, I usually use sentry with [raven-js][1] to track errors. Personally, I think it's the best tool for this right now.

Adding correct debugging pattern within AMD can be tricky at times, I guess a community effort to work on improving knowledge/patterns around this subject could be beneficial.

Is this something you think could be added - in doc at least - within Backbone-Boilerplate project?

If there's positive feedback I can work on a first draft.

  [1]: http://raven-js.readthedocs.org/en/1.0.0/usage/index.html

**Comment by tbranyen** [comment]
Hey @SBoudrias closing this issue since documentation is something I'm trying to scale back on to focus more on the goals of this project.
