### ISSUE TITLE
CRUD application examples using bbb

### ISSUE THREAD

**Issue by alizbazar** [tbranyen/backbone-boilerplate#250]
I was wondering if someone could refer to some existing CRUD examples or simple one-page apps that are built on top of backbone-boilerplate?

While the github-viewer is great, it doesn't really do any write, update or delete operations. Having a sample app that would do those would help a lot novices like me to learn to use backbone with bbb.

**Comment by tbranyen** [comment]
Hrm this is way beyond the scope of this project unfortunately, and there were some good links posted.
