### ISSUE TITLE
Faulty link in Wiki

### ISSUE THREAD

**Issue by sbay** [tbranyen/backbone-boilerplate#253]
There is a faulty non-working link in the Wiki.

It is under Configuration -> Build (Grunt).
https://github.com/backbone-boilerplate/backbone-boilerplate/wiki/Build-%28Grunt%29

**Comment by tbranyen** [comment]
They haven't been written since I have too many other projects to maintain, it's a Wiki so someone else can write them if they have time.  I'm always available to help figure out contents if anyone wants to appear.in, google hangouts, or skype.
