### ISSUE TITLE
Loading "server.js" tasks...ERROR

### ISSUE THREAD

**Issue by august-zou** [tbranyen/backbone-boilerplate#267]
i run grunt,but got this error,anyone can help me.thx.
Loading "server.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

**Comment by blin89** [comment]
+1

**Comment by evanlouie** [comment]
+1

**Comment by victordiaz** [comment]
+1

**Comment by tbranyen** [comment]
Instead of :+1:, can ya'll try and fix the problem and PR? I haven't had time to maintain this project.

**Comment by tbranyen** [comment]
Nevermind, got the open source guilt.  I'm working on a 2.0 release that'll swap out this for the `grunt-contrib-connect` package.

**Comment by tbranyen** [comment]
Fixed in the 2.0.0 branch
