### ISSUE TITLE
JSHint => ESLint

### ISSUE THREAD

**Issue by jmeas** [tbranyen/backbone-boilerplate#271]
With [babel-eslint](https://github.com/babel/babel-eslint), developers can use the full spectrum of Babel features. The maintainer of Babel contributes to that repo, so it's safe to rely on it to stay up-to-date, too. At the moment, it's [an open issue](https://github.com/jshint/jshint/issues/2601) on JSHint to add support for experimental features.

Although I don't necessarily think that it's a good idea that someone use experimental features in a production app, I also don't think that one's tools should decide what one can and can't use.

If you want to stick with JSHint, then it might be worthwhile to add a note somewhere that says that this boilerplate only supports the subset of Babel features supported by JSHint.

I <3<3<3 JSHint, but for the Babel boilerplate I switched to ESLint 'cuz people were wanting to use unsupported things.

**Comment by tbranyen** [comment]
I agree, if we stick with the Babel-ES6 way of doing things, ESLint would be a good idea. Although I'm debating the inclusion of Babel/ES6. I'll open an issue once I have time to think through my thoughts more.

**Comment by tbranyen** [comment]
Not going to implement this myself. Closing this issue.
