### ISSUE TITLE
Application provided as default is initialized twice. 

### ISSUE THREAD

**Issue by leehankyeol** [tbranyen/backbone-boilerplate#273]
Following the cloning repository, `npm install`, and `npm start` without any modification besides adding `console.log()` in `home.js`, I can see two `console.log()` outputs.

## home.js
```
import Component from '../../component';
import template from './home.html';

// Import components.
import '../components/sample-component';

export default Component.extend({
  template,

  initialize: function() {
    this.template.registerPartial('nav', require('../partials/nav.html'));
    console.log('Initialized');
  }
});
```

**Comment by leehankyeol** [comment]
@tbranyen Should I elaborate more on this issue?

**Comment by tbranyen** [comment]
Hi @leehankyeol, sorry GitHub has terrible notification support, only just seeing this now. I'm looking into the problem, I'll comment with what I figure out.

**Comment by tbranyen** [comment]
Looks like our main route is triggered twice on load. Looking into why this is happening.

**Comment by tbranyen** [comment]
Nevermind, threw a log into the route handler and it looks right. Must be something with our page initialization code.

**Comment by tbranyen** [comment]
@leehankyeol Try with this commit: https://github.com/tbranyen/backbone-boilerplate/commit/f3a05cecb20f14925cd76a5ffaa6870c33f65c21 or apply the patch to your current codebase.

**Comment by leehankyeol** [comment]
@tbranyen That fixed the problem right away. Thanks! Should I close the issue?

**Comment by tbranyen** [comment]
sure thing!
