### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by michaelaflores** [tbranyen/backbone-boilerplate#277]
For a starter project there are some pretty quick issues to crop up:
1. JSHint isn't configured to have esnext set to true (easy enough to add to package.json, but should probably be there)
2. Once it _does_ successfully build, some silent error prevents anything from displaying.

I understand this is no longer actively maintained, but it might be worth putting a big warning up that currently it won't build correctly.

**Comment by tbranyen** [comment]
This is no longer true, closing out.
