### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by mylastore** [tbranyen/backbone-boilerplate#279]
Created new view but is not rendering, I follow the home example and created all elements and route.

**Comment by tbranyen** [comment]
Can you send me a link to your repo?

**Comment by mylastore** [comment]
I have this on my local machine is there a way you can show a sample page other than home so see how to handle the view. On my situation I click on the menu link example #sample-page that changes/shows on the URL and if I refresh the browser the page shows.

**Comment by tbranyen** [comment]
I'm on vacation, link me to a repo on GitHub with the source and I'll take a look.
